DADA2 1.28 RELEASE NOTES
-----------------------

#### COMMITS
Date:   Tue Apr 15 10:58:46 2025 -0400

    bump x.y.z version to even y prior to creation of RELEASE_3_21 branch

Date:   Wed Apr 9 14:41:53 2025 -0400

    Fix error introduced in previous commit

    Note to self, don't check in even seemingly trivial changes without running a package check!

Date:   Tue Apr 8 01:22:28 2025 -0400

    Bump

Date:   Tue Apr 8 01:21:13 2025 -0400

    Update errorModels.R

    Remove default values for binnedQ - require the user to pass the binned quality scores to binnedQualErrfun

Date:   Tue Jan 7 20:13:03 2025 -0500

    Update filter.R

    Fixes #2067

Date:   Tue Dec 3 19:04:49 2024 -0500

    moved to makeBinnedQualErrfun

    To work more easily with learnErrors

Date:   Sun Dec 1 16:21:50 2024 -0500

    Added binned quality error model

Date:   Fri Nov 29 19:52:55 2024 -0500

    plotQualityProfile now looks correct with binned quality scores

Date:   Fri Nov 29 19:02:43 2024 -0500

    Merge pull request #1761 from ycl6/convert_integer_to_numeric

    Cast integer objects to numeric type to handle large integers

Date:   Fri Nov 15 05:19:56 2024 -0500

    Bump version

Date:   Thu Nov 14 20:37:09 2024 -0500

    Fixes

Date:   Thu Nov 14 16:35:18 2024 -0500

    Update processing of RDP to allow for species-level reference database

Date:   Wed Nov 13 15:13:03 2024 -0500

    Fix compiler warnings for unused variables

Date:   Wed Nov 13 14:58:35 2024 -0500

    Add function to format GG2 for assignTaxonomy

Date:   Wed Nov 13 12:55:14 2024 -0500

    Minor taxonomy.R updates

Date:   Wed Nov 13 10:59:06 2024 -0500

    Formatting RDP v19 reference

Date:   Tue Nov 12 20:40:11 2024 -0500

    Silva 138.2 update

    Updates to package private functions for digesting Silva release 138.2 into reference files compatible with `assignTaxonomy`.

    NOTE: Still need to update the `assignSpecies` digestion.

Date:   Tue Nov 12 15:37:20 2024 -0500

    Merge branch 'master' of git.bioconductor.org:packages/dada2


`git log d10b12c51b69a58a9e6a3a768fa870bf1abc1950..c21d55cbc9053eecf8e18750ef224961e98f23e0`
