// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __dadac_h__
#define __dadac_h__

#include "dadac_RcppExports.h"

#endif // __dadac_h__
