// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __dadac_RcppExports_h__
#define __dadac_RcppExports_h__

#include <Rcpp.h>

namespace dadac {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("dadac", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("dadac", "dadac_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in dadac");
            }
        }
    }

    inline Rcpp::DataFrame getProbs(Rcpp::NumericMatrix err, std::vector<int> nnt, int maxD) {
        typedef SEXP(*Ptr_getProbs)(SEXP,SEXP,SEXP);
        static Ptr_getProbs p_getProbs = NULL;
        if (p_getProbs == NULL) {
            validateSignature("Rcpp::DataFrame(*getProbs)(Rcpp::NumericMatrix,std::vector<int>,int)");
            p_getProbs = (Ptr_getProbs)R_GetCCallable("dadac", "dadac_getProbs");
        }
        RObject __result;
        {
            RNGScope __rngScope;
            __result = p_getProbs(Rcpp::wrap(err), Rcpp::wrap(nnt), Rcpp::wrap(maxD));
        }
        if (__result.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (__result.inherits("try-error"))
            throw Rcpp::exception(as<std::string>(__result).c_str());
        return Rcpp::as<Rcpp::DataFrame >(__result);
    }

}

#endif // __dadac_RcppExports_h__
