// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __dada2_h__
#define __dada2_h__

#include "dada2_RcppExports.h"

#endif // __dada2_h__
